# Generated by Django 3.2 on 2023-07-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='category/'),
        ),
    ]
