# Generated by Django 3.2 on 2022-11-09 19:53

import article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=article.models.upload_file_path),
        ),
    ]
