# Generated by Django 3.2 on 2022-11-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='short_body',
            field=models.TextField(max_length=500),
        ),
    ]
