# Generated by Django 3.2 on 2022-11-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_tag'),
        ('article', '0004_alter_article_short_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='category.Tag'),
        ),
    ]
