# Generated by Django 3.2 on 2022-12-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_tag'),
        ('article', '0005_article_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(limit_choices_to={'is_active': True}, to='category.Tag'),
        ),
    ]
