# Generated by Django 3.2 on 2023-05-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_alter_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='external_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
