# Generated by Django 3.2 on 2023-05-28 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_tag'),
        ('article', '0008_auto_20230526_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'parent__isnull': False}, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
    ]
